### ISSUE TITLE
Response code of recordServiceRequest

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/ExecutionAndTraceLog#116]
Hello,

I experimented with out implementation of /v1/list-applications-abbreviation, which calls the ExecutionAndTraceLog API recordServiceRequest.

![image](https://user-images.githubusercontent.com/91662447/205314074-b0d292e6-a3eb-4095-ab57-4734f84b542a.png)

I am getting this error log:
recordServiceRequest - record service request with body {"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"ApplicationAbbreviationExtractor","application-release-number":"1.0.0","operation-name":"/v1/list-applications-abbreviation","response-code":200,"timestamp":"2022-12-02T15:08:48+01:00","stringified-body":"{}","stringified-response":"[{\"application-name\":\"OldRelease\",\"application-name-abbreviation\":\"OR\"},{\"application-name\":\"NewRelease\",\"application-name-abbreviation\":\"NR\"},{\"application-name\":\"RegistryOffice\",\"application-name-abbreviation\":\"RO\"},{\"application-name\":\"TypeApprovalRegister\",\"application-name-abbreviation\":\"TAR\"},{\"application-name\":\"ExecutionAndTraceLog\",\"application-name-abbreviation\":\"EATL\"},{\"application-name\":\"OamLog\",\"application-name-abbreviation\":\"OL\"},{\"application-name\":\"AdministratorAdministration\",\"application-name-abbreviation\":\"AA\"},{\"application-name\":\"ApplicationLayerTopology\",\"application-name-abbreviation\":\"ALT\"},{\"application-name\":\"OperationKeyManagement\",\"application-name-abbreviation\":\"OKM\"},{\"application-name\":\"CurrentController\",\"application-name-abbreviation\":\"CC\"}]"} failed with response status: 204

Looking at the implementation in the EATL, there seems to be no possibility to return the response code 200 "OK". Instead it returns 204 on success, which is interpreted as a failure in the onf-code-model-ap:

![image](https://user-images.githubusercontent.com/91662447/205314834-622e4c4b-8624-471c-ae7e-503d40ca8e1b.png)

![image](https://user-images.githubusercontent.com/91662447/205315109-7b8c8941-1a46-4107-a68c-afca4210595d.png)

I guess the fix would be to interpret the 204 response as success.

**Comment by openBackhaul** [comment]
Response code 204 of EaTL://v1/recordServiceRequest should be fine.
No, flaw seen in the specifications.

**Comment by PrathibaJee** [comment]
Many thanks for indicating the problem.

I would like to explain the following things , 
1. The service /v1/record-service-request is responding with 204 as per the expectation in the OAS. So , both specification and the implementation of EATL is fine.
2. **Then why we see the failure “recordServiceRequest - record service request with body …………….. failed with response status: 204” in the console window ?**
In the onf-core-model-ap\applicationPattern\services\ExecutionAndTraceService.js ,  a console log is writing this error message for the response other than 200.
This console log needs to be corrected.

Created a new issue in ApplicationPattern repository to solve this problem https://github.com/openBackhaul/ApplicationPattern/issues/453. So , closing this issue.
Please have a look into the newly created issue as well and let us know your comments.
