### ISSUE TITLE
Complement management requests

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ExecutionAndTraceLog#155]
**Issue is applicable to TAC applications(EATL,OL,ALT,OKM). instead of creating separate issues in all the relevant repositories , first created it in EATL.**

EATL has the following 3 operation-clients(and corresponding FCs) of RO, 

1. **/v1/notify-approvals** --> PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease
2. **/v1/notify-withdrawn-approvals** --> PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease
3. **/v1/end-subscription** --> PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease

This 3 forwarding-constructs which are mapped to the operation-clients dont have a MANAGEMENT fc-port. 
This means , there is no subscription operation available to add this operation-clients to a CONFIGfile.

**Proposals :**
**Proposal#1 :**
One proposal to solve this problem shall be adding individual subscription operations for creating operation-clients and fc-ports for this operations.

**Proposal#2 :**
In the server side , we can introduce a small logic to avoid losing such operation-clients , 
While receiving “update-client” , (the below flow chart only concentrates on the operation-client part)
![image](https://user-images.githubusercontent.com/62344562/208321322-c5f5e0a6-bfe8-4202-963b-fdb9bd44cb93.png)

(for a reference : Similar problem like https://github.com/openBackhaul/OperationKeyManagement/issues/141. )

**Comment by openBackhaul** [comment]
Referencing the following statement:

>Issue is applicable to TAC applications(EATL,OL,ALT,OKM). instead of creating separate issues in all the relevant repositories , first created it in EATL.

The following OperationClients are not associated with an FC:
- **RO:**
TypeApprovalRegister:://v1/redirect-info-about-approval-status-changes
- **TAR:**
RegistryOffice://v1/inquire-application-type-approvals
RegistryOffice://v1/notify-deregistrations
RegistryOffice://v1/end-subscription
- **EaTL + OL + AA + ALT:**
RegistryOffice:://v1/notify-approvals
RegistryOffice:://v1/notify-withdrawn-approvals
RegistryOffice://v1/end-subscription
- **OKM:**
RegistryOffice:://v1/notify-approvals
RegistryOffice:://v1/notify-withdrawn-approvals
ApplicationLayerTopology:://v1/notify-link-updates
RegistryOffice://v1/end-subscription
ApplicationLayerTopology:://v1/end-subscription
ApplicationLayerTopology:://v1/list-end-points-of-link
ApplicationLayerTopology:://v1/list-link-uuids

**Comment by openBackhaul** [comment]
Proposal#3 in short:
- If some application can't reach a consumed service, it contacts RO for updating HttpClient and TcpClient
- After updating HttpClient and TcpClient, it contacts the updated application for updating OperationClients
Existing OperationServices at RO and AP could be re-used after small extensions.

Proposal#3 in detail:
- Some application (A) (not restricted to the case described in the beginning) sporadically consumes another application’s (B) OperationServer
- Suddenly, (A) cannot reach (B) and/or the sporadically consumed OperationServer anymore
- Instantaneously (A) gets into panic and calls RO for help: RO://v1/list-applications
- (here we have a little change: /v1/list-applications needs to be completed either by a list of preceding combinations of application name and release number or (maybe better) by some invariant identifier of applications like e.g. its original name “RegistryOffice”)
- (A) searches the list of applications for the application name and release number of (B)
  - If successful, (A) continuous to use the existing Clients, but with updated TCP/IP addresses (end of story)
- If not successful, (A) searches the list of applications for the invariant identifier of (B)
  - If not successful, (A) feels very much disappointed and decides not to contact RO for an updated list of applications (even if again unsuccessfully attempted to call (B)) for at least 10 minutes
- If (A) would find the invariant identifier of (B) in the list, it would check its HttpClients (remember: created by /v1/regard-application) for same application name and release number.
  - If successful, (A) would use the existing HttpClient and potentially update the TCP/IP address in the TcpClient
  - If not successful, (A) would create HttpClient and TcpClient from the info from /v1/list-applications
- In the next, step (A) calls B://v1/inform-about-application
- (here we would have another little change: /v1/inform-about-application would be complemented by a list of OperationServers. Every OperationServer would need to be identified by a list of preceding operation names or (maybe better) by some invariant identifier like e.g. its original name “NotifyApprovals”)
  - If not successful, (A) does not contact (B) for an updated list of applications (even if again unsuccessfully attempted to call the OperationServer) for at least 10 minutes
- If (A) would find the invariant identifier of the OperationServer in the list, it would update or create its OperationClient and end of story
