### ISSUE TITLE
Maximum service records entries removal from config

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ExecutionAndTraceLog#165]
In v1.0.0 EATL, service record entries were written to load file using profiles. Maximum number of such entries was specified in config file using IntegerProfile. Whenever the number of entries was about to exceed maximum number of entries specified, the oldest entry was removed. See [ServiceRecordProfile.js](https://github.com/openBackhaul/ApplicationPattern/blob/develop/server/applicationPattern/applicationPattern/onfModel/models/profile/ServiceRecordProfile.js) .

Since we are moving to Elasticsearch:
Elasticsearch supports rollover based on various parameters, including maximum number of documents and/or index age, see [Rollovers](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/ilm-rollover.html) and they can even be combined. This is part of the policy configuration, which we already agreed should NOT be part of config file.

Based on the previous statement, I am proposing removing IntegerProfile service from EATL (it's only used for max entries) and keep the maximum number of entries configured directly in Elasticsearch (if needed).

**Comment by openBackhaul** [comment]
@DanaSunal: Could you please confirm that the parameter, which is required for configuring the maximum number of service record entries in Elasticsearch is already covered in the PUT operation of the OAM path 
_/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac/elasticsearch-client-interface-configuration/service-records-policy:_  
(Would it be the _max-size_?)

**Comment by openBackhaul** [comment]
Remove IntegerProfile from ProfileList 
Remove instance of IntegerProfile from ProfileInstanceList 
Remove all paths for managing IntegerProfile from OaM segment of OAS
Remove instance of IntegerProfile for number of records from CONFIGfile.

**Comment by openBackhaul** [comment]
Pull-request #174 merged.
