### ISSUE TITLE
Core-model-construct is failing due to Internal Server Error in testbed

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ExecutionAndTraceLog#220]
**Issue Description :**
While trying to fetch control construct of deployed application in testbed server it is failing with Internal server Error.

**Root cause:**
In server code we are using replaceAll function which is effective from node 16 version . But , in docker file which is used to create the image node 14 version is used .

**Solution:**
To replace docker file that supprots node 16 version.

**Comment by DanaSunal** [comment]
Note: this issue should be in ApplicationPattern (the only occurrence of replaceAll I see is is ElasticsearchService).

Maybe simpler solution would be to use 'replace' instead of 'replaceAll' with regexp and 'g' flag.
`key.replaceAll("_", "-")     =>   key .replace(/_/g, '-')`

**Comment by vanithavalluripalli9** [comment]
Though the replaceAll function in present in AP , the reason for raising the issue in EaTL is changes are required in dockerfile of the application . 

Yeah , agree we can also use the solution mentioned . But woudn't it be more feasible if we shift docker file to node 16 in future . Please, suggest  on how to proceed.

**Comment by DanaSunal** [comment]
Yes, moving to newer version is definitely a good option, but that should be a coordinated effort to upgrade all the applications to node 16, as having some on 14 and some on 16 can cause unknown issues. Upgrading all the applications might be a bigger task (I honestly cannot estimate that) so I thought a code workaround might be a simpler solution for the 2.0.1 release. I am in favor of doing the upgrade after release.
