### ISSUE TITLE
Update release-number of http-c to 2.0.1

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#254]
Current scenario:
In load-file of applications, the http-c/release-number(s) of client applications are 1.0.0.

Problem statement:
Since, the services in v2.0.1 are not backward compatible with v1.0.0, while registering a v2.0.1 of an application, callbacks of /v1/bequeath-your-data-and-die gets failed during data transfer and subscription transfer phases. (because of difference in attribute names or presence of additional attributes).

Related issue : https://github.com/openBackhaul/ApplicationPattern/issues/713

**Comment by openBackhaul** [comment]
Versions updated in AP and all TAC elements
