### ISSUE TITLE
PostTermination - Deep check of CC for being at initial stage checks against old release

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ExecutionAndTraceLog#278]
The errors are either IP addresses not matching (which looks like the fake-ip script issue) or release numbers still being checked
for 1.0.0 despite all of them already on 2.0.1

Provides expected properties in capability class for 'eatl-2-0-1-http-s-000' | 
expected '[{"local-id":"0","release-number":"2.0.1","release-date":"17.12.2021","changes":"Initial version."},{"local-id":"1","release-number":"2.0.1","release-date":"17.12.2022","changes":"Update on ApplicationPattern 2.0.1."}]' 
to equal '[{"local-id":"0","release-number":"1.0.0","release-date":"17.12.2021","changes":"Initial version."},{"local-id":"1","release-number":"2.0.1","release-date":"17.12.2022","changes":"Update on ApplicationPattern 2.0.1."}]'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-es-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-or-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-tar-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-ol-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-aa-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-alt-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

Provides expected properties in configuration class for 'eatl-2-0-1-http-c-okm-1-0-0-000' | expected '2.0.1' to equal '1.0.0'

**Comment by IswaryaaS** [comment]
Shall be fixed in https://github.com/openBackhaul/ExecutionAndTraceLog/pull/322. Kindly reopen if the issue reoccurs
