### ISSUE TITLE
Response code 500 received when protocol is 'HTTPS'

### ISSUE THREAD

**Issue by venkat-nallati** [openBackhaul/ExecutionAndTraceLog#281]
today HTTPS is not supported, but response code should not be 500, expecting 4xx response code instead of 500.

Request body:
{"application-name" : "OperationKeyManagement","release-number" : "2.0.1","protocol" : "HTTPS","address" : {"ip-address":{"ipv-4-address":"127.0.0.1"}},"port" : 3006}

Error logs:
Error: write EPROTO 382E0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

Response Body:
{
    "x-correlator": "a15c4274-becb-01b8-768e-e4c1a127ef7c",
    "trace-indicator": "1.1",
    "user": "*** your name ***",
    "originator": "ExecutionAndTraceLog",
    "application-name": "OperationKeyManagement",
    "release-number": "2.0.1",
    "operation-name": "/v1/redirect-service-request-information",
    "response-code": 500
  },

> Priority:Low;
> AffectedFlow:None;

**Comment by DanaSunal** [comment]
Which API operation is executed? I can't tell that based on the request body only.

**Comment by DanaSunal** [comment]
Also, the response code that should be changed is the one that EATL responds or the response from OKM "/v1/redirect-service-request-information" ?

**Comment by venkat-nallati** [comment]
ServiceLayer / IndividualPart / /v1/regard-application / Acceptance / Update LTP notified? / protocol update
Request URL: http://x.x.x.x:3002/v1/regard-application
request bodies:
{
  "application-name": "ApplicationLayerTopology",
  "release-number": "2.0.1",
  "protocol": "HTTPS",
  "address": {
    "ip-address": {
      "ipv-4-address": "x.x.x.x"
    }
  },
  "port": 3005
}

Logic required in EaTL to send 4xx response instead of 5xx response.

**Comment by DanaSunal** [comment]
FYI regard-application returns 204, the error appears when callback is issued to OKM and OKM is not reachable (via HTTPS).

**Comment by PrathibaJee** [comment]
Issue fixed as a part of the PR https://github.com/openBackhaul/ApplicationPattern/pull/802.
