### ISSUE TITLE
Monitor whether elastic search records are being deleted as per the the service record policy applied.

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/ExecutionAndTraceLog#290]
Currently, in testbed elastic search we are not applying any service record policy for eatl records . So , records are not being deleted and we are not sure whether service-record-policy is working as expected

Can we apply the service record policy for the eatl records and monitor it whether it is working as expected.

**Comment by DanaSunal** [comment]
The REST API is ready to use:

http://localhost:3003/docs/#/ElasticsearchClient/putElasticsearchClientServiceRecordsPolicy

How to create a policy:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/ilm-put-lifecycle.html

Not sure what else is needed from me here.

**Comment by PrathibaJee** [comment]
@Aman , I know that you worked in this activity. Please update the details in this issue.

**Comment by V-Vanitha** [comment]
Service record policy is working as per expectation in  lab environment. 

**Observation** while testing  :  service record policy will only be applied if index-alias is active and number of documents in the index-alias is >0

**Comment by PrathibaJee** [comment]
Thanks for the confirmation. I will close this issue.
