### ISSUE TITLE
Testexecution PostTermination mismatch in the initial and final configuration file - Individual report

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#297]
Assertion failure details
In EATL Individual Services , following are the assertions that are failed because of this problem,

- Provides expected   properties in capability class for 'eatl-2-0-1-http-s-000'
- Provides expected properties in   configuration class for 'eatl-2-0-1-http-c-es-1-0-0-000'
- Provides expected properties in   configuration class for 'eatl-2-0-1-tcp-c-es-1-0-0-000'

Reason :
In the test execution, the expectation is , the initial configuration file should match the final configuration.
But there is a mismatch. This mismatch are consequences of the failures of other assertions. Once the other assertion failures will be resolved , this shall also be cleared.

**Comment by PrathibaJee** [comment]
Since the v2.1.2 doesn't have test suite to validate the failure mentioned in the test execution we cannot validate and close this issue for now.
