### ISSUE TITLE
OAS : OAM layer : incorrect uuid pattern for service-record-profile

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#30]
In OAS specification :: OAM layer,   there is a API request for retrieving service-record-profile-capability 
     "/core-model-1-4:control-construct/profile-collection/profile={uuid}/service-record-profile-1-0:service-record-profile-pac/service-record-profile-capability".
Here, the pattern of uuid is defined as **_pattern: '^eatl-0-0-1-op-s-\d{4}$'_** , which actually could be **_pattern: '^eatl-0-0-1-service-record-p-\d{6}$'_**

**Comment by openBackhaul** [comment]
**Decision:**
Line 2487 with
"pattern: '^eatl-0-0-1-op-s-\d{4}$'"
has to be changed to 
"pattern: '^eatl-0-0-1-service-record-p-\d{6}$'"

**Comment by openBackhaul** [comment]
service records shall be stored into database.
Information model inside database shall be encapsulated by application.
Consequently, there is no service-record-profile anymore and the issue can just be closed.
