### ISSUE TITLE
Typo errors found in spec files

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#331]
- [x]  As per decision made on https://github.com/openBackhaul/ApplicationPattern/issues/836, instances of _CurrentController shall be expected to be removed_ from specification files. 
     - There are few occurrences of CurrentController instances in [forwardings.yaml](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json) file. These shall be removed.
     
- [x] In [forwardings.yaml](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json), in INPUT fc-port of forwarding-construct _ServiceRequestCausesLoggingRequest_, we shall need to add the following services.

   - eatl-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
   - eatl-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
   - eatl-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release
   
- [x] Since, /v1/update-client-of-subsequent-release could update ltp instances in load file, this shall be eligible for sending a LTP Update request to ALT. In forwarding-construct _ServiceRequestCausesLtpUpdateRequest_, /v1/update-client-of-subsequent-release (eatl-2-1-0-op-s-bm-015) is to be added into INPUT fc-port list.
This change is required in both [forwardings.yaml](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json) files.

- [ ] In [forwardings.yaml](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json) files, forwarding _ServiceRequestCausesLtpDeletionRequest_, we shall need to add the operation-server uuid of /v1/disregard-application -- eatl-2-1-0-op-s-is-002 as it is responsible for deleting ltp instances in load file.

- [x] In [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json), the instance eatl-2-1-0-http-c-or-2-0-1-000 shall be updated with attribute values application-name as "ExecutionAndTraceLog" and release-number as "2.0.1"

**Comment by openBackhaul** [comment]
/v1/disregard-application will not be addressed by the RO v2.1.1 anymore.
Marked it also Deprecated in all TAC applications.

Apart from that, changed as proposed.
