### ISSUE TITLE
Observation regarding EaTL server unavailability

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ExecutionAndTraceLog#35]
When EaTL application goes down , 
**Impact :** 
- Service records from other applications will not be captured
- Even after coming live , the lost records will not be recovered.

**Note :** 
When EaTL is down , it’s very difficult to identify this. Until we manually try to use this application.

### Proposal for High availability :
**Proposal#1 :** If we are planning to continue with docker engine , a simple shell script that 
- monitors the pid of the application’s port
- starts the container if the pid is not available
(already we have such scripts for other applications like traffic checker. Monitoring dashboard)

**Proposal#2 :** If we are planning to move to an orchestrator(docker swarm, Kubernetes) then the orchestrator will take care of it.

### Proposal to prevent data loss :
Including a message broker(like rabbitmq) that buffers the message until the EaTL application is available again. (But of course the message broker should also be highly available)
Reference : https://microservices.io/patterns/communication-style/messaging.html

![image](https://user-images.githubusercontent.com/62344562/171720373-a6d870d1-21a6-4a2e-9e23-d9e32dd4c66c.png)

> Priority: low

**Comment by PrathibaJee** [comment]
Decision during SDN application call on 1st of July : 

For the availability problem considering the Proposal#1(effort would be minimal as the same concept is already available for other applications like traffic checker). 
Also , need to observe the v1/register-yourself scenario during the kick-start of the container.

**Comment by PrathibaJee** [comment]
Currently CICD engineer included a High Availability script that monitors the PID of the containers and brings it back whenever it goes to unavailability. High level information about this script is available in this [document ](https://github.com/openBackhaul/ApplicationPattern/blob/61ecdca2f3b36c1d82e7075e1ae764c499236eb3/doc/TestingApplications/TestingApplications.md#hascripts).

Further keeping this issue open under milestone v2.0.0_impl to observe the applications availability in the version 2.0.0 implementation.

**Comment by PrathibaJee** [comment]
@sunil-kumar-meena , please close this issue if the High Availability script solves the problem described. Thanks.

**Comment by sunil-kumar-meena** [comment]
EATL is being handled by High Availability script
