### ISSUE TITLE
Request for making timestamp mandatory attribute in serviceRequestRecord schema 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#350]
In OAS of ExecutionAndTraceLog, we have the services _/v1/record-service-request, /v1/list-records, /v1/list-records-of-flow, /v1/list-records-of-unsuccessful_ using the schema "**_serviceRequestRecord_**". This schema has following structure
```
required:
        - x-correlator
        - trace-indicator
        - user
        - originator
        - application-name
        - release-number
        - operation-name
        - response-code
optional:
        - timestamp
        - stringified-body
        - stringified-response
        - url
        - exec-time
```

Proposal: 
Since, the attribute "**_timestamp_**" plays a crucial role in many aspect of debugging and monitoring, requesting to include this attribute in required section. So, this will allow all users to send logs along with timestamp to ExecutionAndTraceLog application.

**Comment by openBackhaul** [comment]
Changed as proposed.
