### ISSUE TITLE
Request to include attributes as search criteria in rest API

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#351]
In OAS of ExecutionAndTraceLog, we have the services _/v1/record-service-request, /v1/list-records, /v1/list-records-of-flow, /v1/list-records-of-unsuccessful_ using the schema "**_serviceRequestRecord_**". This schema has following structure
```
required:
        - x-correlator
        - trace-indicator
        - user
        - originator
        - application-name
        - release-number
        - operation-name
        - response-code
optional:
        - timestamp
        - stringified-body
        - stringified-response
        - url
        - exec-time
```

Among the above attributes, the following attributes are often required for searching few records. 
```
- username (the actual user who is triggering the request to know the number of request an user has triggered or the list of requests the user has requested in the system)
- timestamp - from time and to time (to figure out the records that have been recorded in given time period - usually required from performance testing perspective)
- operation-name (to figure out the frequency that an operation has been requested in system - usually required from testing perspective)
- application-name and release-number (to identify the requests that have been triggered to an application)
```

Proposal: 
Since the above attributes are often required as parameters for filtering the records in EATL, we shall include a rest API operation-server in EATL application, that could take attributes in such a way that the request body can accept any of the given attributes specified in list (one or more or combination of attributes). So that the application could use those keywords to query the records in Elasticsearch. 
Kindly let me know your views.

**Comment by openBackhaul** [comment]
Changed as proposed.
