### ISSUE TITLE
Typo error in config.json file

### ISSUE THREAD

**Issue by at00825957** [openBackhaul/ExecutionAndTraceLog#355]
In version 2.1.1 [config.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog%2Bconfig.json) file, TypeApprovalRegister operation-client uuid ('eatl-2-1-0-op-c-im-tar-2-1-0-004') of /v1/redirect-service-request-information has the wrong server-ltp ('eatl-2-1-0-http-c-eatl-2-0-1-000') of ExecutionAndTraceLog.

Instead of this server-ltp ('eatl-2-1-0-http-c-eatl-2-0-1-000') it should be server-ltp ('eatl-2-1-0-http-c-tar-2-1-0-000')

**Comment by openBackhaul** [comment]
Corrected as proposed.
