### ISSUE TITLE
Implementation of /v1/list-records shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#401]
The specification of /v1/list-records has been updated to have multiple attributes in request-body. 
It is added with "searched-user", "start-of-searched-period", "end-of-searched-period", "searched-operation-name", "searched-application-name" and "searched-release-number". 

- Support to these attributes shall be implemented for filtering from Elasticsearch in such a way that 
     - if individual attributes are present in request-body, the filter is applied only for that attribute
     - except for "searched-release-number", it is always expected to be a combination with "searched-application-name". If only "searched-release-number" is received, it could be rejected  
     - if combination of attributes are present in request-body, they should be filtered accordingly.

**Comment by PrathibaJee** [comment]
In older index of EATL2.1.1 , we have records with / without timestamp , so after moving/upgrading EATL in the live to 2.1.2, maximum for 5 days there is a possibility that  /v1/list-records validation will fail if a single record is without timestamp. To avoid this , we can have default invalid value that represents that the timestamp field is not available.
