### ISSUE TITLE
Forwarding should not be sent if it is unable to fetch the operation-name while formulating the request body of forwarding.

### ISSUE THREAD

**Issue by V-Vanitha** [openBackhaul/ExecutionAndTraceLog#416]
**Issue Description:**

When /v1/regard-application is executed it will create http-c , op-c , tcp-c for the regarded application in config file and /v1/add-operation-client-to-link fowarding will be sent. 

The request body for the forwarding /v1/add-operation-client-to-link  is formulated by fetching the operation-name of the regarded application . 

If it is unable to fetch the operation-name for some reason , the forwarding should not be processed further.

**Comment by at00825957** [comment]
Completed in below PR.

https://github.com/openBackhaul/ExecutionAndTraceLog/pull/418
