### ISSUE TITLE
Load file : detailed-logging-is-on attribute to be removed from logical-termination-point instances

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#47]
As per understanding, detailed-logging-is-on attribute is applicable only for the operation "/v1/record-service-request" of ExecutionAndTraceLog

Problem Description:
In load-file, [ExecutionAndTraceLog_0.0.2_tsi.211217.1630+data.2.json](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/ExecutionAndTraceLog_0.0.2_tsi.211217.1630%2Bdata.2.json),  for ltp instance eatl-0-0-1-op-c-2040  contains an additional attribute _detailed-logging-is-on_, which needs to be removed.

Note : 
- eatl-0-0-1-op-c-2040 refers to /v1/redirect-service-request-information

Related issues:
https://github.com/openBackhaul/ApplicationLayerTopology/issues/63
https://github.com/openBackhaul/AdministratorAdministration/issues/40
https://github.com/openBackhaul/OperationKeyManagement/issues/32
https://github.com/openBackhaul/OamLog/issues/41

**Comment by openBackhaul** [comment]
Friday call on 12.08.: Attribute shall just be removed from LOADfiles where it is not required.

**Comment by openBackhaul** [comment]
Changed as proposed (pushed into openBackhaul/issue112).
