### ISSUE TITLE
Retrieving data should support pagination

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ExecutionAndTraceLog#49]

**Comment by MartinSunal** [comment]
Integration of ES to EaTL returns maximum 1000 oldest records https://github.com/openBackhaul/ExecutionAndTraceLog/pull/46
ES supports pagination to retrieve another set of records but the pagination is not exposed in EaTL REST API.
Pagination could be added as query params to REST URL.

info about pagination in ES:
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html
