### ISSUE TITLE
server: service-record-profile uuid to be updated 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ExecutionAndTraceLog#53]
As per issue https://github.com/openBackhaul/ExecutionAndTraceLog/issues/30, the uuid pattern is decided to be updated from ^eatl-0-0-1-op-s-\d{4}$ to ^eatl-0-0-1-service-record-p-\d{6}$.

Problem statement:
As per the decision, the server-side code is updated to create service-record-profile entries having uuid(s) with 6 digits. 
This tends to be problem when there is a difference in server-code and /api/openApi.yaml file in server. 
Additionally, due to presence of "op-s" in uuid pattern instead of "service-record-p", it gives 400 error on trying to access data from OAM layer

proposal 1: Update server-logic to create 4-digit uuid suffix 
proposal 2: Update api/openapi.yaml file for uuid pattern of service-record-profile to have ^eatl-0-0-1-service-record-p-\d{6}$

**Comment by PrathibaJee** [comment]
Issue resolved by the changes delivered in the PullRequest https://github.com/openBackhaul/ExecutionAndTraceLog/pull/55. Hence closing the issue.
