### ISSUE TITLE
To transfer ElasticSearchClient information to new release during /v1/bequeath-your-data-and-die

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ExecutionAndTraceLog#93]
In the Elastic search , currently we removed the forwarding PromptForBequeathingDataCausesTransferOfListOfRecords  from /v1/bequeath-your-data-and-die service. This is good as practically it is not good to transfer all the records via REST from the previous version to new version.

Can we include a mechanism to transfer the details of the ElasticSearchClient  from the oldRelease to newRelease ? 
so that the configured ElasticSearchClient information and the index details from the oldRelease can be passed to the newRelease and we can access the previously stored records.

If this transfer of ElasticSearchClient from oldRelease  to newRelease via REST is not preferred.
we can try to include a script during the startup of the newRelease  to configure the “elasticsearch-client-interface-configuration” via OAM layer with the following required information , 
•	auth
•	index-alias
•	service-records-policy

Also kindly please let me know if already a procedure is planned which I overlooked in the specification and if not can we discuss regarding this subject further. Many thanks.

**Comment by openBackhaul** [comment]
> Can we include a mechanism to transfer the details of the ElasticSearchClient from the oldRelease to newRelease ?  
Yes, such transfer of the details of the ElasticSearchClient from the oldRelease to newRelease is planned.
Transfer via REST is preferred.

Whether to schedule into AP v2.0.0 or AP v3.0.0 is undecided (v3.0.0 more likely).

**Comment by PrathibaJee** [comment]
Many thanks for providing your views.

Since version 1.0.0 don’t have ElasticSearchClient information stored in the CONFIG file, in version 2.0.0 there will not be much utilization if we include this mechanism. Including this in v3.0.0 should be fine. 

Meanwhile , if we include any patch release for example 2.0.1, manually we can make the new version to point to the expected alias using the OAM services.

**Comment by openBackhaul** [comment]
Agree with your points.

**Comment by PrathibaJee** [comment]
Thanks for creating the issue https://github.com/openBackhaul/ApplicationPattern/issues/435. 
Closing this issue as https://github.com/openBackhaul/ApplicationPattern/issues/435 covers the required change.
