### ISSUE TITLE
Support Version 2.0.0 changes for /v1/bequeath-your-data-and-die

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ExecutionAndTraceLog#98]
1. Generate server stub for the version 2.0.0 specification 
2. If the api/openapi.yaml is not updated as per the published version 2.0.0 , then copy the api/openapi.yaml file from the generated stub to the source code
3. no change required in the method signature
4. Bequeath-your-data-and-die service will process the request , and checks if the "application-name" in the request-body matches the "http-server-interface-capability/application-name". **This functionality should be removed.**
    **Changes required :**
    In server/services/individualServicesService.js need to remove check for application-name for bequeath-your-data-and-die service.

5. In bequeath-your-data-and-die logic to update the parameters of new release using the forwardingName PromptForBequeathingDataCausesTransferOfListOfApplications , new release ltp instance shall be traced. 

6. Bequeath-your-data-and-die service should update the incoming request parameters.
  **Changes required :**
    In server/services/individualServicesService.js need to set the the parameters by calling respective set functions of the parameters.

Following tasks needs to be completed to support /v1/bequeath-your-data-and-die version 2.0.0 , 
- [ ] https://github.com/openBackhaul/ExecutionAndTraceLog/issues/94
- [ ] https://github.com/openBackhaul/ExecutionAndTraceLog/issues/95
- [x] https://github.com/openBackhaul/ExecutionAndTraceLog/issues/96
- [x] https://github.com/openBackhaul/ExecutionAndTraceLog/issues/97
- [ ] https://github.com/openBackhaul/ExecutionAndTraceLog/issues/164

**Comment by DanaSunal** [comment]
@vanithavalluripalli9  Point 4: 'Bequeath-your-data-and-die service will process the request , and checks if the "application-name" in the request-body matches the "http-server-interface-capability/application-name". This functionality should be removed.' conflicts with issue #96 .  What is the motivation for removing the check?

**Comment by vanithavalluripalli9** [comment]
The reason for point 4 is as per the current specification application-name is configurable and it might get updated which means that application name might change from the existing one . So we can remove the application name check.
It sure contradicts with issue #96 which is not valid in current scenario we can close the issue as not valid.
